### ISSUE TITLE
플레이어의 이동 관련(윤석)

### ISSUE THREAD

**Issue by CHeonNoePung** [ycs-202007005/Ref_Shooting_Game#1]
방향키를 꾹 누를 시 딜레이 없이 일정한 속도로 이동할수 있도록 한다.
플레이어가 대각선으로도 움직일수 있도록 한다.

**Comment by ycs-202007055** [comment]
구현완료 화면크기 정해지면 그거에 맞게 s, d 이동 범위 정해주면 됨
