### ISSUE TITLE
스테이지, 적 생성(윤석)

### ISSUE THREAD

**Issue by CHeonNoePung** [ycs-202007005/Ref_Shooting_Game#9]
테스트용 스테이지를 생성하고 그 안에 적들을 생성한다.
스테이지 내부에서 적을 배치하고 움직이게 한다.
일반 적 2기와 보스급 적을 만들고 생성한다.
각각의 일반 적은 서로 다른 움직임, 다른 공격을 갖도록 한다.
보스는 다른 적들과 달리 충돌해도 사라지지 않는 판정을 가진다.

**Comment by ycs-202007055** [comment]
완성
